version: '3.4'

services:
  retrocacheapi:
    image: ${DOCKER_REGISTRY-}retrocacheapi
    build:
      context: .
      dockerfile: RetroCacheApi/Dockerfile

  retrocache:
    image: ${DOCKER_REGISTRY-}retrocache
    build:
      context: .
      dockerfile: RetroCache/Dockerfile
    expose:
    - 80
    ports:
     - 80:80
